:source-highlighter: highlightjs

= Cypress

== Introducción a Cypress

=== ¿Qué es Cypress?

Cypress es una herramienta de código abierto que permite realizar pruebas de extremo a extremo (E2E) de forma rápida, sencilla y confiable. Es un framework de pruebas que se ejecuta en el navegador y funciona en cualquier pila de desarrollo o framework.

=== Ventajas y características principales

Cypress es un framework de pruebas de extremo a extremo para aplicaciones web modernas. A continuación se presentan algunas de las ventajas y características principales de Cypress:

* *Arquitectura única:* Cypress utiliza una arquitectura única que se ejecuta en el mismo bucle de eventos que la aplicación bajo prueba. Esto le permite tener un control completo y realizar acciones en tiempo real, lo que resulta en una ejecución más rápida y confiable de las pruebas.
* *Fácil instalación y configuración:* Cypress es fácil de instalar y configurar. Solo requiere unas pocas líneas de código para configurar el entorno de prueba y comenzar a escribir pruebas.
* *Interfaz de usuario amigable:* Cypress ofrece una interfaz de usuario amigable y fácil de usar. Proporciona una vista en tiempo real de la ejecución de las pruebas, lo que facilita la depuración y la identificación de problemas.
* *Selección inteligente de elementos:* Cypress utiliza selectores inteligentes para identificar y seleccionar elementos en la página. Puede seleccionar elementos mediante etiquetas HTML, clases, atributos y otros criterios, lo que facilita la escritura de pruebas precisas y mantenibles.
* *Pruebas en tiempo real:* Cypress permite observar y depurar las pruebas en tiempo real a medida que se ejecutan. Proporciona instantáneas automáticas y videos de las pruebas, lo que facilita la identificación y corrección de errores.
* *Facilidad de escritura de pruebas:* Cypress utiliza una sintaxis sencilla y fácil de entender para escribir pruebas. Proporciona comandos encadenados y funciones intuitivas que facilitan la creación de escenarios de prueba complejos.
* *Depuración y tiempo de ejecución más rápidos:* Cypress permite la depuración paso a paso y la recarga automática de la página durante la ejecución de las pruebas. Esto agiliza el proceso de depuración y reduce el tiempo necesario para ejecutar las pruebas.
* *Visibilidad completa del estado de la aplicación:* Cypress proporciona una visibilidad completa del estado de la aplicación bajo prueba en cada paso de la ejecución de la prueba. Esto facilita la comprensión y verificación del comportamiento esperado de la aplicación.
* *Integración con otras herramientas:* Cypress se integra fácilmente con otras herramientas populares de desarrollo y prueba, como frameworks de pruebas (Jest, Mocha), herramientas de construcción (Webpack, Babel) y sistemas de control de versiones (Git).

=== Instalación y configuración del entorno de trabajo

.Cyress se puede instalar de dos formas:
* Mediante el gestor de paquetes npm
* Mediante el gestor de paquetes yarn

.Instalación con npm
[source,shell]
```
npm install cypress --save-dev
```

.Instalación con yarn
[source,shell]
```
yarn add cypress --dev
```

== Configuración y estructura de proyectos en Cypress

=== Configuración inicial del proyecto

Con Cypress podemos crear un proyecto desde cero o utilizar un proyecto existente. 

.Para crear un proyecto desde cero, podemos ejecutar el siguiente comando:
[source,shell]
```
cypress open
```

.Para utilizar un proyecto existente, podemos ejecutar el siguiente comando:
[source,shell]
```
cypress open --project path/to/project
```

=== Cypress con TypeScript

Cypress es compatible con TypeScript. Para utilizar TypeScript en Cypress, debemos inicializar el proyecto con TypeScript y configurar el archivo de configuración de Cypress para que utilice TypeScript.

.Para inicializar el proyecto con TypeScript, podemos ejecutar el siguiente comando:
[source,shell]
```
npm install typescript --save-dev
npx tsc --init
```

.En el archivo tsconfig.json, podemos añadir la siguiente configuración:
[source,json]
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"]
  },
  "include": ["**/*.ts"]
}
```

.En package.json, podemos añadir los siguientes scripts:
[source,json]
```
"scripts": {
    "cypress:open": "cypress open",
    "cypress:run": "cypress run"
}
```

.Podemos crear un test de prueba, con el siguiente contenido:
[source,typescript]
```
it('should perform basic google search', () => {
  cy.visit('https://google.com');
  cy.get('[name="q"]')
    .type('subscribe')
    .type('{enter}');
});
```

=== Organización de archivos y carpetas

.Cypress organiza los archivos y carpetas de la siguiente manera:
* *cypress.config.js:* Archivo de configuración de Cypress.
* *cypress:* Carpeta principal del proyecto.
** *fixtures:* Carpeta que contiene los datos de prueba.
** *e2e:* Carpeta que contiene las pruebas de extremo a extremo.
** *support:* Carpeta que contiene los archivos de soporte.

=== Uso de gestores de dependencias (npm)

Podemos incorporar el uso de cypress en nuestro proyecto mediante el gestor de paquetes npm, incluyendo en los scripts del package.json diferentes comandos para ejecutar las pruebas.

.En el caso de npm, podemos añadir a los scripts del package.json el siguiente comando:
[source,json]
```
"scripts": {
    "cypress:open": "cypress open", // Abre la interfaz de usuario de Cypress
    "cypress:run": "cypress run", // Ejecuta las pruebas en modo headless
    "cypress:verify": "cypress verify", // Verifica la instalación de Cypress
    "cypress:version": "cypress version", // Muestra la versión de Cypress
    "cypress:info": "cypress info", // Muestra información sobre Cypress
}
```

=== Configuración de plugins y complementos

Existen varios plugins útiles disponibles para Cypress que pueden ampliar su funcionalidad y facilitar el proceso de prueba. 

.A continuación, se presentan algunos de los principales plugins de Cypress:
* *cypress-axe:* Este plugin permite realizar pruebas de accesibilidad en tus aplicaciones web utilizando la biblioteca axe-core. Ayuda a identificar y corregir problemas de accesibilidad en tu código.
* *cypress-cucumber-preprocessor:* Permite escribir pruebas en estilo BDD (Behavior-Driven Development) utilizando el lenguaje Gherkin. Esto facilita la colaboración entre equipos de desarrollo y QA al proporcionar una sintaxis más legible y orientada al negocio.
* *cypress-file-upload:* Permite simular la carga de archivos en tus pruebas de Cypress. Puedes seleccionar archivos locales y adjuntarlos a elementos de entrada de archivos en tu aplicación.
* *cypress-image-snapshot:* Ayuda a realizar pruebas de regresión visual comparando imágenes capturadas de tu aplicación con imágenes de referencia previamente guardadas. Esto permite detectar cambios visuales no deseados en tu interfaz.
* *cypress-iframe:* Proporciona métodos y comandos para interactuar con iframes en Cypress. Facilita la escritura de pruebas para contenido dentro de iframes y la manipulación de elementos dentro de ellos.
* *cypress-localstorage-commands:* Permite acceder y manipular los datos almacenados en el Local Storage de tu navegador durante las pruebas. Esto es útil cuando necesitas verificar o modificar valores almacenados en el Local Storage de tu aplicación.
* *cypress-plugin-snapshots:* Proporciona funcionalidad de instantáneas (snapshots) para capturar y comparar datos y elementos en tus pruebas. Puedes usarlo para verificar cambios en la estructura HTML, valores de objetos JavaScript, respuestas de API, entre otros.
* *cypress-commands:* Agrega comandos personalizados a Cypress para realizar acciones comunes en tus pruebas, como iniciar sesión, interactuar con elementos específicos de tu aplicación, esperar condiciones personalizadas, entre otros.

==== Instalación de plugins

.Para instalar un plugin, podemos ejecutar el siguiente comando:
[source,shell]
```
npm install cypress-image-snapshot --save-dev
```

Ahora, para utilizar el plugin en tus pruebas de Cypress, abre un archivo de prueba existente o crea uno nuevo dentro de la carpeta cypress/integration.

.Importa el plugin en la parte superior del archivo de prueba. Agrega la siguiente línea al principio del archivo:
[source,shell]
```
import 'cypress-image-snapshot/command';
```

.Ya puedes usar el plugin en tus pruebas. Por ejemplo, para capturar una instantánea de un elemento, puedes usar el siguiente comando:
```
describe('Ejemplo de uso de cypress-image-snapshot', () => {
  it('debería coincidir con la imagen de referencia', () => {
    cy.visit('/ruta-a-tu-pagina');

    cy.get('.mi-elemento').should('be.visible');

    cy.get('.mi-elemento').toMatchImageSnapshot();
  });
});
```
== Bloques de construcción de pruebas en Cypress

Los bloques de construcción de pruebas en Cypress se utilizan para organizar y estructurar las pruebas de forma clara y coherente. Estos bloques permiten definir el flujo de ejecución de las pruebas y establecer las condiciones iniciales y finales de cada test.

.A continuación, se describen los bloques de construcción principales y su uso en Cypress:

* *describe:* El bloque describe se utiliza para agrupar los tests que tienen una misma funcionalidad. Se utiliza para definir una suite de pruebas y proporcionar un contexto para los tests relacionados.
* *context:* El bloque context se utiliza para agrupar los tests dentro de un bloque describe. Se utiliza para organizar los tests en subgrupos lógicos y proporcionar una estructura jerárquica a las pruebas.
* *it:* El bloque it se utiliza para definir un test. Dentro de este bloque se definen los pasos que se ejecutarán para validar el test.
* *before:* El bloque before se utiliza para definir los pasos que se ejecutarán antes de todos los tests. Se utiliza para configurar el entorno de prueba común a todos los tests.
* *beforeEach:* El bloque beforeEach se utiliza para definir los pasos que se ejecutarán antes de cada test. Se utiliza para configurar el entorno de prueba específico para cada test.
* *after:* El bloque after se utiliza para definir los pasos que se ejecutarán después de todos los tests. Se utiliza para limpiar y liberar los recursos utilizados durante la ejecución de los tests.
* *afterEach:* El bloque afterEach se utiliza para definir los pasos que se ejecutarán después de cada test. Se utiliza para limpiar y restablecer el entorno de prueba después de cada test.

.Un ejemplo de estructura de tests con Cypress sería:
```
describe('Ejemplo de estructura de tests', () => {
  before(() => {
    // Se ejecuta antes de todos los tests
  });

  beforeEach(() => {
    // Se ejecuta antes de cada test
  });

  after(() => {
    // Se ejecuta después de todos los tests
  });

  afterEach(() => {
    // Se ejecuta después de cada test
  });

  context('Contexto 1', () => {
    it('Test 1', () => {
      // Test 1
    });

    it('Test 2', () => {
      // Test 2
    });
  });

  context('Contexto 2', () => {
    it('Test 3', () => {
      // Test 3
    });

    it('Test 4', () => {
      // Test 4
    });
  });
});
```

== Interacción con elementos de la interfaz

=== Localización de elementos

El primer paso para interactuar con los elementos de la interfaz de usuario en Cypress es localizarlos en la página web. Para ello, podemos utilizar selectores CSS, selectores XPath, selectores de atributos, selectores de texto, entre otros. No siempre es necesario utilizar selectores complejos, ya que Cypress proporciona métodos y comandos para localizar elementos de forma sencilla y eficiente.


Tenemos la función cy.visit() que nos permite visitar una página web. 

Un ejemplo en una estructura de tests con Cypress sería:
```
describe('Ejemplo de estructura de tests', () => {
  context('Contexto 1', () => {
    it('Test 1', () => {
      cy.visit('https://www.google.com');
    });
  });
});
```

.Para localizar elementos en la interfaz, podemos usar la función cy.get().
```
describe('Ejemplo de estructura de tests', () => {
  context('Contexto 1', () => {
    it('Test 1', () => {
      cy.visit('https://www.google.com');

      cy.get('input[name="q"]');
    });
  });
});
```

.La función cy.get() nos permite localizar elementos por:
* id
* class
* name
* tag
* atributos
* selectores CSS

.Un ejemplo con todos estos tipos de localización sería:
```
describre('Ejemplo con todos los selectores: ', () => {
  it('Ejemplo de localización por id', () => {
    cy.get('#id');
  });

  it('Ejemplo de localización por class', () => {
    cy.get('.class');
  });

  it('Ejemplo de localización por name', () => {
    cy.get('[name="name"]');
  });

  it('Ejemplo de localización por tag', () => {
    cy.get('input');
  });

  it('Ejemplo de localización por atributo', () => {
    cy.get('[data-cy="data-cy"]');
  });

  it('Ejemplo de localización por selector CSS', () => {
    cy.get('input[name="name"]');
  });
});
```

=== Interacción con elementos

En Cypress tenemos una serie de acciones para interaccionar con los elementos de la interfaz.

.Los tipos de acciones que podemos realizar son:
* *click*: hace click en un elemento 
* *dblclick*: hace doble click en un elemento
* *check*: marca un checkbox
* *uncheck*: desmarca un checkbox
* *clear*: limpia el contenido de un elemento
* *type*: escribe en un elemento
* *select*: selecciona una opción de un elemento select
* *trigger*: dispara un evento en un elemento
* *invoke*: invoca una función en un elemento
* *scrollIntoView*: hace scroll hasta un elemento
* *focus*: hace focus en un elemento
* *blur*: hace blur en un elemento
* *submit*: envía un formulario

.Un ejemplo de interacción con un elemento sería:
```
describe('Ejemplo de interacción con elementos', () => {
  it('Ejemplo de click', () => {
    cy.get('button').click();
  });

  it('Ejemplo de doble click', () => {
    cy.get('button').dblclick();
  });

  it('Ejemplo de check', () => {
    cy.get('input[type="checkbox"]').check();
  });

  it('Ejemplo de uncheck', () => {
    cy.get('input[type="checkbox"]').uncheck();
  });

  it('Ejemplo de clear', () => {
    cy.get('input[type="text"]').clear();
  });

  it('Ejemplo de type', () => {
    cy.get('input[type="text"]').type('Texto de ejemplo');
  });

  it('Ejemplo de select', () => {
    cy.get('select').select('Opción 1');
  });

  it('Ejemplo de trigger', () => {
    cy.get('button').trigger('click');
  });

  it('Ejemplo de invoke', () => {
    cy.get('button').invoke('attr', 'disabled');
  });

  it('Ejemplo de scrollIntoView', () => {
    cy.get('button').scrollIntoView();
  });

  it('Ejemplo de focus', () => {
    cy.get('input[type="text"]').focus();
  });

  it('Ejemplo de blur', () => {
    cy.get('input[type="text"]').blur();
  });

  it('Ejemplo de submit', () => {
    cy.get('form').submit();
  });
});
```

=== Validación de elementos

.Para validar que un elemento es visible, podemos usar la función cy.get().should('be.visible').
```
describe('Ejemplo de validación de elementos visibles', () => {
  it('Ejemplo de validación de elementos visibles', () => {
    cy.get('button').should('be.visible');
  });
});
```

.Las posibles validaciones que podemos hacer son:
* *be.visible*: el elemento es visible
* *be.hidden*: el elemento está oculto
* *be.checked*: el elemento está marcado
* *be.disabled*: el elemento está deshabilitado
* *be.enabled*: el elemento está habilitado
* *be.empty*: el elemento está vacío
* *be.exist*: el elemento existe
* *be.focused*: el elemento tiene el foco
* *be.selected*: el elemento está seleccionado
* *be.visible*: el elemento es visible
* *be.not.visible*: el elemento no es visible
* *be.not.checked*: el elemento no está marcado
* *be.not.disabled*: el elemento no está deshabilitado
* *be.not.empty*: el elemento no está vacío
* *be.not.exist*: el elemento no existe
* *be.not.focused*: el elemento no tiene el foco
* *be.not.selected*: el elemento no está seleccionado
* *be.not.visible*: el elemento no es visible
* *have.attr*: el elemento tiene un atributo
* *have.class*: el elemento tiene una clase
* *have.css*: el elemento tiene una propiedad CSS
* *have.data*: el elemento tiene un atributo data
* *have.descendants*: el elemento tiene descendientes
* *have.focus*: el elemento tiene el foco
* *have.id*: el elemento tiene un id
* *have.length*: el elemento tiene una longitud
* *have.prop*: el elemento tiene una propiedad
* *have.text*: el elemento tiene un texto
* *have.value*: el elemento tiene un valor


.Un ejemplo de validación de elementos sería:
```
describe('Ejemplo de validación de elementos', () => {
  it('Ejemplo de validación de elementos visibles', () => {
    cy.get('button').should('be.visible');
  });

  it('Ejemplo de validación de elementos ocultos', () => {
    cy.get('button').should('be.hidden');
  });

  it('Ejemplo de validación de elementos marcados', () => {
    cy.get('input[type="checkbox"]').should('be.checked');
  });

  it('Ejemplo de validación de elementos deshabilitados', () => {
    cy.get('button').should('be.disabled');
  });

  it('Ejemplo de validación de elementos habilitados', () => {
    cy.get('button').should('be.enabled');
  });

  it('Ejemplo de validación de elementos vacíos', () => {
    cy.get('input[type="text"]').should('be.empty');
  });

  it('Ejemplo de validación de elementos existentes', () => {
    cy.get('button').should('be.exist');
  });

  it('Ejemplo de validación de elementos con foco', () => {
    cy.get('input[type="text"]').should('be.focused');
  });

  it('Ejemplo de validación de elementos seleccionados', () => {
    cy.get('select').should('be.selected');
  });
});
```

.Un ejemplo de validación de texto sería:
[source,javascript]
```
describe('Ejemplo de validación de texto', () => {
  it('Ejemplo de validación de texto', () => {
    cy.get('button').should('have.text', 'Texto de ejemplo');
  });
});
```

.Un ejemplo de validación de atributos sería:
[source,javascript]
```
describe('Ejemplo de validación de atributos', () => {
  it('Ejemplo de validación de atributos', () => {
    cy.get('button').should('have.attr', 'disabled');
  });
});
```

=== Esperas explícitas e implícitas

.Las esperas explícitas son aquellas que se realizan en un punto concreto del código. Por ejemplo, si queremos esperar a que un elemento sea visible, podemos hacerlo de la siguiente forma:
[source,javascript]
```
describe('Ejemplo de espera explícita', () => {
  it('Ejemplo de espera explícita', () => {
    cy.get('button').should('be.visible');
  });
});
```

.Las esperas implícitas son aquellas que se realizan de forma automática. Por ejemplo, si queremos esperar a que un elemento sea visible, podemos hacerlo de la siguiente forma:
[source,javascript]
```
describe('Ejemplo de espera implícita', () => {
  it('Ejemplo de espera implícita', () => {
    cy.get('button').click();
    cy.wait(1000);
    cy.get('button').should('be.visible');
  });
});
```

=== Fixtures y datos de prueba

Las fixtures son archivos JSON que contienen datos de prueba que se pueden utilizar en las pruebas de Cypress. Estos archivos se almacenan en la carpeta fixtures del proyecto y se pueden cargar en las pruebas utilizando la función cy.fixture().

.Los fixtures son útiles cuando deseas:

* **Simular respuestas de una API:** En lugar de hacer solicitudes reales a una API, puedes cargar respuestas simuladas desde archivos de fixtures.
* **Proporcionar datos de prueba:** Puedes tener un conjunto de datos específicos para ejecutar tus pruebas y validarlas.
* **Reducir la dependencia de fuentes externas:** Al usar datos locales en lugar de datos en vivo, tus pruebas serán más rápidas y confiables.

.Un ejemplo de uso de fixtures sería:
[source,javascript]
```
describe('Ejemplo de uso de fixtures', () => {
  it('Ejemplo de uso de fixtures', () => {
    cy.fixture('example.json').then((data) => {
      cy.log(data);
    });
  });
});
```

.Siendo el contenido del archivo example.json:
[source,json]
```
{
  "name": "Ejemplo",
  "description": "Esto es un ejemplo de fixture"
}
```

=== Variables y alias

En Cypress, podemos utilizar variables y alias para almacenar y reutilizar valores en nuestras pruebas. Las variables nos permiten almacenar valores y reutilizarlos en diferentes partes de la prueba, mientras que los alias nos permiten asignar un nombre a un elemento y referenciarlo posteriormente.

.Las variables se pueden declarar y utilizar de la siguiente forma:
```
describe('Ejemplo de uso de variables', () => {
  it('Ejemplo de uso de variables', () => {
    const
      username = 'usuario',
      password = 'contraseña';

    cy.get('input[name="username"]').type(username);
    cy.get('input[name="password"]').type(password);
  });
});
```

.Los alias se pueden declarar y utilizar de la siguiente forma:
```
describe('Ejemplo de uso de alias', () => {
  it('Ejemplo de uso de alias', () => {
    cy.get('button').as('boton');
    cy.get('@boton').click();
  });
});
```

=== Comandos personalizados

En Cypress, podemos crear comandos personalizados para realizar acciones comunes en nuestras pruebas. Estos comandos nos permiten encapsular la lógica de prueba en funciones reutilizables y mejorar la legibilidad y mantenibilidad de las pruebas.

.Para crear un comando personalizado, podemos hacer lo siguiente:
```
Cypress.Commands.add('login', (username, password) => {
  cy.get('input[name="username"]').type(username);
  cy.get('input[name="password"]').type(password);
  cy.get('button').click();
});
```

.Y para utilizar el comando personalizado, podemos hacer lo siguiente:
```
describe('Ejemplo de uso de comandos personalizados', () => {
  it('Ejemplo de uso de comandos personalizados', () => {
    cy.login('usuario', 'contraseña');
  });
});
```

=== Pruebas condicionales

Podemos realizar pruebas condicionales para validar el comportamiento de la aplicación en diferentes escenarios. Las pruebas condicionales nos permiten ejecutar diferentes acciones en función de una condición específica y validar el resultado esperado.

.Para realizar una prueba condicional, podemos hacer lo siguiente:
```
describe('Ejemplo de prueba condicional', () => {
  it('Ejemplo de prueba condicional', () => {
    cy.get('button').then(($button) => {
      if ($button.is(':visible')) {
        cy.log('El botón es visible');
      } else {
        cy.log('El botón no es visible');
      }
    });
  });
});
```

=== Pruebas asincrónicas

Las pruebas asincrónicas son aquellas que requieren esperar a que se complete una operación asíncrona antes de continuar con la ejecución de la prueba. En Cypress, podemos utilizar comandos y funciones asincrónicas para manejar operaciones asíncronas y asegurarnos de que las pruebas se ejecuten correctamente.

.Para realizar una prueba asincrónica, podemos hacer lo siguiente:
```
describe('Ejemplo de prueba asincrónica', () => {
  it('Ejemplo de prueba asincrónica', () => {
    cy.get('button').click().then(() => {
      cy.log('El botón ha sido clicado');
    });
  });
});
```

=== Pruebas de regresión visual

Las pruebas de regresión visual son aquellas que comparan imágenes capturadas de la aplicación con imágenes de referencia previamente guardadas. Estas pruebas permiten detectar cambios visuales no deseados en la interfaz de usuario y garantizar que la aplicación se vea como se espera en diferentes escenarios.

.Para realizar una prueba de regresión visual, podemos hacer lo siguiente:
```
describe('Ejemplo de prueba de regresión visual', () => {
  it('Ejemplo de prueba de regresión visual', () => {
    cy.get('.mi-elemento').toMatchImageSnapshot();
  });
});
```

=== Pruebas de API

Las pruebas de API son aquellas que validan el comportamiento de una API en diferentes escenarios. Estas pruebas permiten verificar que la API responde correctamente a las solicitudes y devuelve los datos esperados.

Usamos la función cy.request() para realizar una solicitud a una API y validar la respuesta, el estado y los datos devueltos por la API. cy.request() devuelve una promesa que podemos manejar con then() y realizar las validaciones necesarias.

.Los métodos que podemos utilizar para realizar pruebas de API son:
* *GET*: cy.request('GET', 'https://api.example.com/data')
* *POST*: cy.request('POST', 'https://api.example.com/data', { data: 'example' })
* *PUT*: cy.request('PUT', 'https://api.example.com/data', { data: 'example' })
* *DELETE*: cy.request('DELETE', 'https://api.example.com/data')
* *PATCH*: cy.request('PATCH', 'https://api.example.com/data', { data: 'example' })
* *HEAD*: cy.request('HEAD', 'https://api.example.com/data')
* *OPTIONS*: cy.request('OPTIONS', 'https://api.example.com/data')

.Para realizar una prueba de API, podemos hacer lo siguiente:
```
describe('Ejemplo de prueba de API', () => {
  it('Ejemplo de prueba de API', () => {
    cy.request('GET', 'https://api.example.com/data').then((response) => {
      expect(response.status).to.eq(200);
      expect(response.body).to.have.property('data');
    });
  });
});
```

=== Gestión de errores

Podemos gestionar errores y excepciones para manejar situaciones inesperadas y garantizar que las pruebas se ejecuten correctamente. Podemos utilizar comandos y funciones de Cypress para capturar errores, mostrar mensajes de error y realizar acciones en caso de fallo.

Uno de los mecanismos que podemos utilizar para gestionar errores es cy.on('fail', () => {}), que nos permite capturar errores y realizar acciones personalizadas en caso de fallo.

.Para gestionar errores en Cypress, podemos hacer lo siguiente:
```
describe('Ejemplo de gestión de errores', () => {
  it('Ejemplo de gestión de errores', () => {
    cy.on('fail', (error) => {
      cy.log(error.message);
    });

    cy.get('button').click();
  });
});
```
